[suricata]
enabled   = true
filter    = suricata
logpath   = /var/log/suricata/eve.json
maxretry  = 1
findtime  = 3600
bantime   = 86400
action    = nftables-allports[name=suricata, table=safehaven, chain=input]
