table inet safehaven {
	set addr-set-suricata {
		type ipv4_addr
	}

	chain input {
		type filter hook input priority filter; policy drop;
		iifname "lo" accept
		ct state established,related accept
		iifname "tailscale0" accept
		iifname "wlan1" tcp dport 22 drop
		iifname "wlan1" accept
		iifname "wlan0" tcp dport 22 accept
		iifname "wg0" accept
		udp dport 51820 accept
		udp dport 41641 accept
		drop
		meta l4proto tcp ip saddr @addr-set-suricata reject with icmp port-unreachable
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
		iifname "wlan1" oifname "wlan0" accept
		iifname "wlan1" oifname "wg0" accept
		iifname "wg0" oifname "wlan0" accept
		iifname "wlan0" ct state established,related accept
		iifname "wg0" ct state established,related accept
		iifname "tailscale0" accept
		oifname "tailscale0" accept
	}

	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oifname "wlan0" masquerade
	}

	chain prerouting {
		type nat hook prerouting priority dstnat; policy accept;
		iifname "wlan1" udp dport 53 dnat ip to 10.42.0.1
		iifname "wlan1" tcp dport 53 dnat ip to 10.42.0.1
	}
}
table ip filter {
	chain INPUT {
		type filter hook input priority filter; policy accept;
		counter packets 1975050 bytes 208688487 jump ts-input
	}

	chain FORWARD {
		type filter hook forward priority filter; policy accept;
		counter packets 0 bytes 0 jump ts-forward
	}

	chain OUTPUT {
		type filter hook output priority filter; policy accept;
	}

	chain ts-input {
		ip saddr 100.122.225.109 iifname "lo" counter packets 0 bytes 0 accept
		ip saddr 100.115.92.0/23 iifname != "tailscale0" counter packets 0 bytes 0 return
		ip saddr 100.64.0.0/10 iifname != "tailscale0" counter packets 0 bytes 0 drop
		iifname "tailscale0" counter packets 50345 bytes 3818426 accept
		udp dport 41641 counter packets 54854 bytes 7448302 accept
	}

	chain ts-forward {
		iifname "tailscale0" counter packets 0 bytes 0 meta mark set mark and 0xff00ffff xor 0x40000
		meta mark & 0x00ff0000 == 0x00040000 counter packets 0 bytes 0 accept
		ip saddr 100.64.0.0/10 oifname "tailscale0" counter packets 0 bytes 0 drop
		oifname "tailscale0" counter packets 0 bytes 0 accept
	}
}
table ip nat {
	chain ts-postrouting {
		meta mark & 0x00ff0000 == 0x00040000 counter packets 0 bytes 0 masquerade
	}

	chain POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;
		counter packets 8891 bytes 648022 jump ts-postrouting
	}
}
table ip6 filter {
	chain ts-input {
		ip6 saddr fd7a:115c:a1e0::537:e16d iifname "lo" counter packets 0 bytes 0 accept
		iifname "tailscale0" counter packets 0 bytes 0 accept
		udp dport 41641 counter packets 0 bytes 0 accept
	}

	chain ts-forward {
		iifname "tailscale0" counter packets 0 bytes 0 meta mark set mark and 0xff00ffff xor 0x40000
		meta mark & 0x00ff0000 == 0x00040000 counter packets 0 bytes 0 accept
		oifname "tailscale0" counter packets 0 bytes 0 accept
	}

	chain INPUT {
		type filter hook input priority filter; policy accept;
		counter packets 1015 bytes 109477 jump ts-input
	}

	chain FORWARD {
		type filter hook forward priority filter; policy accept;
		counter packets 0 bytes 0 jump ts-forward
	}
}
table ip6 nat {
	chain ts-postrouting {
		meta mark & 0x00ff0000 == 0x00040000 counter packets 0 bytes 0 xt target "MASQUERADE"
	}

	chain POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;
		counter packets 152 bytes 13898 jump ts-postrouting
	}
}
